#################### ALUMNOS ################

### Obtencion de todos los alumnos
GET http://127.0.0.1:5000/alumnos

### Obtencion un alumno
GET http://127.0.0.1:5000/alumnos/1

### Guardado de un alumno
POST http://127.0.0.1:5000/alumnos
Content-Type: application/json

{
        "dni": 45136672,
        "names": "ELIZABETH",
        "surnames": "GABRIELA",
        "address": "Calle Flores, 456",
        "email": "patricio.estebanez@example.com",
        "active": true
    }
### Borrado de un alumno
DELETE  http://127.0.0.1:5000/alumnos/4

### Edicion de un alumno
PATCH http://127.0.0.1:5000/alumnos/17
Content-Type: application/json

    {
    "surnames":"1A Quito"
    }

#################### TUTORES ################

### Obtencion de todos los tutores
GET http://127.0.0.1:5000/tutores

### Obtencion un tutor
GET http://127.0.0.1:5000/tutores/3

### Guardado de un tutor
POST http://127.0.0.1:5000/tutores
Content-Type: application/json

{
    "dni": 12000002,
    "names": "PAPA Esteban",
    "surnames": "Tomatote",
    "address": "Calle Principal, 123",
    "email": "papa.esteban.tomatote@example.com",
    "student_id":1,
    "active": true
}
### Borrado de un tutor
DELETE  http://127.0.0.1:5000/tutores/4

### Edicion de un tutor
PATCH http://127.0.0.1:5000/tutores/1
Content-Type: application/json

    {
    "student_id" : [1, 2]
    }

### Asignacion de tutor a un alumno
POST http://127.0.0.1:5000/alumnos/1/tutores/1



#################### CURSOS ################

### Obtencion todos los cursos
GET http://127.0.0.1:5000/cursos

### Obtencion un curso por id
GET http://127.0.0.1:5000/cursos/3

### Guardado de un curso
POST http://127.0.0.1:5000/cursos
Content-Type: application/json

{
    "level": 3,
    "division": "C",
    "year": 2023,
    "current": true,
    "active": true
}

### Borrado de un curso
DELETE http://127.0.0.1:5000/cursos/3

### Edicion de un curso
PATCH http://127.0.0.1:5000/cursos/1
Content-Type: application/json

{
    "division": "A"
}

### Asociar alumno a un curso
POST http://127.0.0.1:5000/cursos/5/alumno/51



#################### ASISTENCIA ################

### Obtener todas las asistencias
GET http://127.0.0.1:5000/asistencias

### Obtener todas las asistencias inactivas
GET http://127.0.0.1:5000/asistencias/inactivas

### Borrar asistencias por id
DELETE http://127.0.0.1:5000/asistencias/1

#### Definir endpoint para crear una asistencia

POST http://127.0.0.1:5000/asistencias
Content-Type: application/json

{
    "course_id": 1,
    "student_id": 2,
    "state": true,
    "active": true
}

### Cerrar asistencia del dia
POST http://127.0.0.1:5000/asistencias/cerrar/1


### Revision Asistencia de un curso un dia especifico
POST http://127.0.0.1:5000/asistencias/revision
Content-Type: application/json

{
    "course_id": 1,
    "date_to_search":"2023/12/04"
}


#################### USUARIOS ################

POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
    "username": "martin",
    "password": "passmartin",
    "fullname": "Martin Cardozo",
    "rol": "Secretario"
}

### Login
POST http://127.0.0.1:5000/auth
Content-Type: application/json

{
    "username": "martin",
    "password": "passmartin"
}