"""Associated user field added, accesslevel created

Revision ID: 508e39abde5c
Revises: c5215ca7ae40
Create Date: 2024-11-25 11:27:09.978151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508e39abde5c'
down_revision = 'c5215ca7ae40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['associated_user'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('access_level')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('associated_user')

    # ### end Alembic commands ###
