"""empty message

Revision ID: 549efa64e071
Revises: 3c885e5e6f64
Create Date: 2023-11-07 11:11:47.977493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549efa64e071'
down_revision = '3c885e5e6f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.drop_constraint('tutor_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tutor_student_id_fkey', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
