"""Associated user field added, accesslevel created2

Revision ID: f185c74cc79c
Revises: 508e39abde5c
Create Date: 2024-11-25 11:50:29.675455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f185c74cc79c'
down_revision = '508e39abde5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('associated_user',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_level',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('associated_user',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
