"""empty message

Revision ID: f9e977b123ae
Revises: ae7de5346bbe
Create Date: 2023-12-03 11:30:54.085272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e977b123ae'
down_revision = 'ae7de5346bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_courses',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_course_id_fkey', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('students_course_id_fkey', 'courses', ['course_id'], ['id'])

    op.drop_table('students_courses')
    # ### end Alembic commands ###
